AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - bin/*
    - 'vendor/**/*'

Documentation:
  Enabled: false

Layout/IndentationWidth:
  Width: 2

Metrics/LineLength:
  Max: 120

# Be realistic, sometimes a class has many lines
Metrics/ClassLength:
  Enabled: true
  Max: 150

# Should be deprecated in newer Rails-versions
Style/FrozenStringLiteralComment:
  Enabled: false
