AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
    - 'Guardfile'

Documentation:
  Enabled: false

Layout/IndentationWidth:
  Width: 2

Layout/LeadingCommentSpace:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - '**/*.rake'
    - 'test/**/*.rb'

# Be realistic, sometimes a class has many lines
Metrics/ClassLength:
  Enabled: true
  Max: 150

# Should be deprecated in newer Rails-versions
Style/FrozenStringLiteralComment:
  Enabled: false
